name: Build And Deploy vue3-composition-admin

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          yarn
          yarn build:prod
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.VUE3_ACCESS_TOKEN }}
          publish_dir: docs/.vuepress/dist
